### ISSUE TITLE
How to activate Celery beat?

### ISSUE THREAD

**Issue by AnderUstarroz** [docker-library/celery#11]
Is there a way to also activate the beat in the docker container?? It's a key feature for Celery

**Comment by jiamicu** [comment]
I think you may need change `CMD ["celery", "worker"]` to `CMD ["celery","beat"]`
Rebuild the image and then you can use`docker run --link some-rabbit:rabbit --name some-celery -d celery` to run the beat.

**Comment by tianon** [comment]
I was going through old PRs, and ended up filing https://github.com/docker-library/celery/issues/12 as a result -- if you've got time, please go check my assumptions before we deprecate this image entirely. :heart: :pray:

**Comment by tianon** [comment]
See https://github.com/docker-library/docs/pull/880 for more details of the deprecation of this image.
