### ISSUE TITLE
Keyerror when importing .pyc files

### ISSUE THREAD

**Issue by derrend** [docker-library/celery#7]
I'm trying to only mount the essential files into the container from the outside like so:

```
-v /celeryconfig.py:/home/user/celeryconfig.py:ro \
-v /cpop/cpop/settings.py:/home/user/cpop/settings.py:ro \
-v /cpop/popsite/tasks.py:/home/user/popsite/tasks.py:ro
```

which works fine.
problem is if i compile the .py files into .pyc and change the mount options like so:

```
-v /celeryconfig.pyc:/home/user/celeryconfig.pyc:ro \
-v /cpop/cpop/settings.pyc:/home/user/cpop/settings.pyc:ro \
-v /cpop/popsite/tasks.pyc:/home/user/popsite/tasks.pyc:ro
```

it breaks.
Can anyone suggest why this might be?

**Comment by tianon** [comment]
I _think_ `.pyc` files are more Python-version-specific than one might expect (although I readily admit my Python-fu isn't as strong as it should be, especially at this low level).  Have you tried using the `celery` container itself to compile the `.pyc` files to ensure that the Python version matches exactly?

**Comment by derrend** [comment]
I think I figured it out, sort of. The container is running python 3 which doesn't seem to compile .pyc files and put them in the same directory, instead it compiles them with a very different name (not .pyc) and places them in a subdirectory which broke my scripts because my django project and other network containers use python 2.7 so my `from <module> import <file>.pyc` lines were failing.

I still ended up using the uncompiled source code. I will try and remember to post an update if I find a more effective fix.

Thanks for the help :)

**Comment by tianon** [comment]
I'm going to close this (especially since you figured out an effective workaround that appears to be more to upstream's preference), but feel free to comment again if you do find a fix you're happier with. :smile:
